const mongoose=require('mongoose')
 const videoSchema=new mongoose.Schema({
    userid:{
        type:String,
        Required:true,
        unique:true
    },
    title:{
        type:String,
        Required:true
    },
    desc:{
        type:String,
        Required:true,
    },
    imgUrl:{
        type:String,
        Required:true,
    },
    videoUrl:{
        type:String,
        Required:true
    },
    views:{
        type:Number,
        Required:true,
    },
    tags:{
        type:String,
        Required:true,
    }, 
    like:{
        type:Number,
        default:0
    },
    dislike:{
        type:Number,
        default:0
    }, 
 },{timestamp:true})

 module.exports=mongoose.model('video',videoSchema)